apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - name: http
      port: 80
      targetPort: 11434
      protocol: TCP
      nodePort: 30007
